package com.adam.iptvplayer

import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.util.concurrent.Executors

class MainActivity : AppCompatActivity() {
    private val io=Executors.newFixedThreadPool(3); private lateinit var prefs:android.content.SharedPreferences
    private var repo:IptvRepository?=null; private var server=""; private var user=""; private var pass=""
    private val bg=Color.rgb(8,10,19); private val card=Color.rgb(20,24,38); private val soft=Color.rgb(29,34,51); private val gold=Color.rgb(241,174,52); private val cyan=Color.rgb(38,190,210)
    override fun onCreate(b:Bundle?){super.onCreate(b);prefs=getSharedPreferences("iptv_profile_v1",MODE_PRIVATE);server=prefs.getString("server","")?:"";user=prefs.getString("user","")?:"";pass=prefs.getString("pass","")?:"";if(server.isBlank()||user.isBlank()||pass.isBlank())login()else{repo=IptvRepository(server,user,pass);home()}}

    private fun login(){
        val root=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setBackgroundColor(bg);setPadding(dp(34),dp(24),dp(34),dp(24))}
        val hero=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(22),0,dp(42),0)}
        hero.addView(t("ADAM",15,true,gold));hero.addView(t("IPTV PLAYER",38,true,Color.WHITE));hero.addView(t("Watch your world. Your way.",18,false,Color.rgb(174,180,196)));hero.addView(t("Live television, movies and series in one elegant player.",13,false,Color.rgb(116,124,145)).apply{setPadding(0,dp(10),0,dp(28))})
        val chips=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};listOf("LIVE TV","MOVIES","SERIES").forEach{chips.addView(chip(it),LinearLayout.LayoutParams(0,dp(42),1f).apply{marginEnd=dp(8)})};hero.addView(chips)
        root.addView(hero,LinearLayout.LayoutParams(0,-1,1.05f))
        val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(30),dp(24),dp(30),dp(24));background=round(card,26)}
        box.addView(t("Welcome back",25,true,Color.WHITE));box.addView(t("Sign in with your Xtream Codes account",13,false,Color.rgb(135,143,163)).apply{setPadding(0,dp(4),0,dp(10))})
        val es=e("Server URL",server,false);val eu=e("Username",user,false);val ep=e("Password",pass,true);box.addView(es);box.addView(eu);box.addView(ep)
        val status=t("",12,false,Color.rgb(190,196,210));box.addView(status)
        val connect=btn("SIGN IN",gold,Color.rgb(15,16,24));connect.setOnClickListener{val s=es.text.toString().trim();val u=eu.text.toString().trim();val p=ep.text.toString();if(s.isBlank()||u.isBlank()||p.isBlank()){status.text="Please complete all fields";return@setOnClickListener};status.text="Connecting…";connect.isEnabled=false;io.execute{try{val x=IptvRepository(s,u,p).authenticate();if((x.optJSONObject("user_info")?.optInt("auth",0)?:0)!=1)error("Account not accepted");server=s.trimEnd('/');user=u;pass=p;prefs.edit().putString("server",server).putString("user",user).putString("pass",pass).apply();repo=IptvRepository(server,user,pass);runOnUiThread{home()}}catch(ex:Exception){runOnUiThread{connect.isEnabled=true;status.text="Connection failed • ${ex.message}"}}}}
        box.addView(connect,LinearLayout.LayoutParams(-1,dp(54)).apply{topMargin=dp(12)});box.addView(t("Player only • No channels are included with this app",11,false,Color.rgb(94,102,120)).apply{gravity=Gravity.CENTER;setPadding(0,dp(13),0,0)})
        root.addView(box,LinearLayout.LayoutParams(0,-1,.95f));setContentView(root)
    }

    private fun home(){
        val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(28),dp(17),dp(28),dp(18))}
        val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val logo=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};logo.addView(t("ADAM",19,true,gold));logo.addView(t("  IPTV",19,true,Color.WHITE));top.addView(logo,LinearLayout.LayoutParams(0,-2,1f));top.addView(t("● ONLINE   $user",12,true,Color.rgb(85,218,153)),LinearLayout.LayoutParams(-2,-2));val set=btn("⚙",soft,Color.WHITE);set.setOnClickListener{settings()};top.addView(set,LinearLayout.LayoutParams(dp(52),dp(42)).apply{marginStart=dp(14)});root.addView(top)
        val welcome=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(0,dp(20),0,dp(14))};welcome.addView(t("Good to see you",13,false,Color.rgb(126,134,154)));welcome.addView(t("What do you want to watch?",25,true,Color.WHITE));root.addView(welcome)
        val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};row.addView(tile("◉","LIVE TV","Watch channels",Color.rgb(23,111,142)){browser("live")},lp());row.addView(tile("▶","MOVIES","Explore your library",Color.rgb(117,58,155)){browser("vod")},lp());row.addView(tile("▤","SERIES","Seasons & episodes",Color.rgb(184,87,45)){browser("series")},lp());row.addView(tile("★","FAVORITES","Your saved content",Color.rgb(62,91,142)){favorites()},lp(last=true));root.addView(row,LinearLayout.LayoutParams(-1,0,1f))
        val bottom=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(0,dp(12),0,0)};bottom.addView(t("ADAM IPTV  •  Premium Player  •  v1.1",11,false,Color.rgb(88,96,115)),LinearLayout.LayoutParams(0,-2,1f));bottom.addView(t("Long-press content to add to Favorites",11,false,Color.rgb(88,96,115)));root.addView(bottom);setContentView(root)
    }
    private fun lp(last:Boolean=false)=LinearLayout.LayoutParams(0,-1,1f).apply{if(!last)marginEnd=dp(12)}
    private fun tile(icon:String,title:String,sub:String,color:Int,action:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.BOTTOM;setPadding(dp(20),dp(18),dp(20),dp(20));background=round(color,22);isFocusable=true;setOnClickListener{action()};addView(t(icon,34,true,Color.WHITE),LinearLayout.LayoutParams(-2,0,1f));addView(t(title,20,true,Color.WHITE));addView(t(sub,12,false,Color.argb(205,255,255,255)))}

    private fun browser(kind:String){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(24),dp(14),dp(24),dp(16))};val bar=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val back=btn("‹",soft,Color.WHITE);back.setOnClickListener{home()};bar.addView(back,LinearLayout.LayoutParams(dp(50),dp(44)));bar.addView(t(when(kind){"live"->"Live TV";"vod"->"Movies";else->"Series"},24,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f).apply{marginStart=dp(15)});val search=e("Search","",false);bar.addView(search,LinearLayout.LayoutParams(dp(250),dp(46)));root.addView(bar);val body=LinearLayout(this);val cats=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val cs=ScrollView(this).apply{addView(cats)};val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val ls=ScrollView(this).apply{addView(list)};body.addView(cs,LinearLayout.LayoutParams(dp(225),-1).apply{topMargin=dp(13);marginEnd=dp(12)});body.addView(ls,LinearLayout.LayoutParams(0,-1,1f).apply{topMargin=dp(13)});root.addView(body,LinearLayout.LayoutParams(-1,0,1f));setContentView(root);var items:List<IptvRepository.Item> = emptyList();var cat="all";fun render(){list.removeAllViews();items.filter{(cat=="all"||it.categoryId==cat)&&it.name.contains(search.text.toString(),true)}.forEach{list.addView(item(it),LinearLayout.LayoutParams(-1,dp(68)).apply{bottomMargin=dp(7)})}};search.setOnKeyListener{_,_,_->render();false};io.execute{try{val c=repo!!.categories(kind);items=repo!!.items(kind);runOnUiThread{c.forEach{x->val b=btn(x.name,soft,Color.WHITE);b.gravity=Gravity.START or Gravity.CENTER_VERTICAL;b.setOnClickListener{cat=x.id;render()};cats.addView(b,LinearLayout.LayoutParams(-1,dp(48)).apply{bottomMargin=dp(6)})};render()}}catch(ex:Exception){runOnUiThread{list.addView(t("Unable to load content\n${ex.message}",15,false,Color.LTGRAY))}}}}
    private fun item(i:IptvRepository.Item)=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(17),0,dp(17),0);background=round(card,14);isFocusable=true;addView(t(if(fav(i))"★" else "☆",20,true,gold),LinearLayout.LayoutParams(dp(42),-2));addView(t(i.name,15,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f));addView(t(if(i.kind=="series")"EPISODES  ›" else "PLAY  ▶",11,true,Color.rgb(146,154,173)));setOnClickListener{if(i.kind=="series")episodes(i)else play(repo!!.streamUrl(i),i.name)};setOnLongClickListener{toggle(i);Toast.makeText(this@MainActivity,if(fav(i))"Added to favorites" else "Removed from favorites",Toast.LENGTH_SHORT).show();true}}
    private fun episodes(s:IptvRepository.Item){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(25),dp(16),dp(25),dp(16))};val b=btn("‹ SERIES",soft,Color.WHITE);b.setOnClickListener{browser("series")};root.addView(b,LinearLayout.LayoutParams(dp(130),dp(44)));root.addView(t(s.name,24,true,Color.WHITE).apply{setPadding(0,dp(14),0,dp(12))});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(ScrollView(this).apply{addView(list)},LinearLayout.LayoutParams(-1,0,1f));setContentView(root);io.execute{try{val eps=repo!!.episodes(s.id);runOnUiThread{eps.forEach{x->val r=btn(x.title,card,Color.WHITE);r.gravity=Gravity.START or Gravity.CENTER_VERTICAL;r.setOnClickListener{play(repo!!.episodeUrl(x),x.title)};list.addView(r,LinearLayout.LayoutParams(-1,dp(56)).apply{bottomMargin=dp(6)})}}}catch(_:Exception){}}}
    private fun favorites(){val a=prefs.getStringSet("favorites",emptySet())?:emptySet();if(a.isEmpty()){Toast.makeText(this,"No favorites yet",Toast.LENGTH_SHORT).show();return};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(25),dp(16),dp(25),dp(16))};val b=btn("‹ HOME",soft,Color.WHITE);b.setOnClickListener{home()};root.addView(b,LinearLayout.LayoutParams(dp(120),dp(44)));root.addView(t("Favorites",25,true,Color.WHITE).apply{setPadding(0,dp(14),0,dp(12))});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(ScrollView(this).apply{addView(list)},LinearLayout.LayoutParams(-1,0,1f));a.forEach{raw->try{val o=JSONObject(raw);val x=IptvRepository.Item(o.getString("id"),o.getString("name"),null,o.optString("ext"),o.optString("cat"),o.getString("kind"));list.addView(item(x),LinearLayout.LayoutParams(-1,dp(68)).apply{bottomMargin=dp(7)})}catch(_:Exception){}};setContentView(root)}
    private fun settings(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setBackgroundColor(bg);setPadding(dp(100),dp(25),dp(100),dp(25))};root.addView(t("Account & Settings",27,true,Color.WHITE));root.addView(t("Xtream account\n$user\n$server\n\nADAM IPTV Player  •  v1.1.0",14,false,Color.rgb(155,162,180)).apply{gravity=Gravity.CENTER;setPadding(0,dp(18),0,dp(22))});val h=btn("BACK TO HOME",gold,Color.rgb(20,20,25));h.setOnClickListener{home()};root.addView(h,LinearLayout.LayoutParams(dp(260),dp(52)));val out=btn("REMOVE ACCOUNT",Color.rgb(122,45,57),Color.WHITE);out.setOnClickListener{prefs.edit().remove("server").remove("user").remove("pass").apply();server="";user="";pass="";repo=null;login()};root.addView(out,LinearLayout.LayoutParams(dp(260),dp(50)).apply{topMargin=dp(10)});setContentView(root)}
    private fun play(url:String,title:String){startActivity(Intent(this,PlayerActivity::class.java).putExtra("url",url).putExtra("title",title))}
    private fun json(i:IptvRepository.Item)=JSONObject().put("id",i.id).put("name",i.name).put("ext",i.extension).put("cat",i.categoryId).put("kind",i.kind).toString()
    private fun fav(i:IptvRepository.Item)=prefs.getStringSet("favorites",emptySet())?.any{try{val o=JSONObject(it);o.optString("id")==i.id&&o.optString("kind")==i.kind}catch(_:Exception){false}}==true
    private fun toggle(i:IptvRepository.Item){val s=(prefs.getStringSet("favorites",emptySet())?:emptySet()).toMutableSet();val old=s.firstOrNull{try{val o=JSONObject(it);o.optString("id")==i.id&&o.optString("kind")==i.kind}catch(_:Exception){false}};if(old==null)s.add(json(i))else s.remove(old);prefs.edit().putStringSet("favorites",s).apply()}
    private fun chip(s:String)=TextView(this).apply{text=s;textSize=11f;setTextColor(Color.rgb(200,205,217));gravity=Gravity.CENTER;background=round(soft,12);typeface=Typeface.DEFAULT_BOLD}
    private fun t(s:String,z:Int,b:Boolean,c:Int)=TextView(this).apply{text=s;textSize=z.toFloat();setTextColor(c);if(b)typeface=Typeface.DEFAULT_BOLD}
    private fun e(h:String,v:String,secret:Boolean)=EditText(this).apply{hint=h;setHintTextColor(Color.rgb(108,116,136));setTextColor(Color.WHITE);setText(v);setSingleLine();textSize=14f;background=round(soft,13);setPadding(dp(16),0,dp(16),0);if(secret)inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD;layoutParams=LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(9)}}
    private fun btn(s:String,bg:Int,fg:Int)=Button(this).apply{text=s;setTextColor(fg);textSize=12f;typeface=Typeface.DEFAULT_BOLD;isAllCaps=false;background=round(bg,13);isFocusable=true}
    private fun round(c:Int,r:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat()}
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    override fun onDestroy(){super.onDestroy();io.shutdownNow()}
}
