package com.adam.iptvplayer

import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.Editable
import android.text.InputType
import android.text.TextWatcher
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import org.json.JSONObject
import java.util.concurrent.Executors

class MainActivity:AppCompatActivity(){
    private val io=Executors.newFixedThreadPool(4);private lateinit var prefs:android.content.SharedPreferences;private var repo:IptvRepository?=null;private var server="";private var user="";private var pass=""
    private val bg=Color.rgb(6,8,13);private val panel=Color.rgb(16,19,28);private val soft=Color.rgb(28,32,44);private val gold=Color.rgb(229,184,92)
    override fun onCreate(b:Bundle?){super.onCreate(b);prefs=getSharedPreferences("iptv_profile_v1",MODE_PRIVATE);server=prefs.getString("server","")?:"";user=prefs.getString("user","")?:"";pass=prefs.getString("pass","")?:"";if(server.isBlank()||user.isBlank()||pass.isBlank())login()else{repo=IptvRepository(server,user,pass);home()}}

    private fun login(){val root=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setBackgroundColor(bg);setPadding(dp(42),dp(30),dp(42),dp(30))};val left=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(24),0,dp(70),0)};left.addView(t("ADAM IPTV",36,true,Color.WHITE));left.addView(t("A clean player for your own IPTV service.",16,false,Color.rgb(155,161,177)).apply{setPadding(0,dp(8),0,dp(20))});left.addView(t("LIVE  •  MOVIES  •  SERIES",12,true,gold));root.addView(left,LinearLayout.LayoutParams(0,-1,1.15f));val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(30),dp(24),dp(30),dp(24));background=round(panel,22)};box.addView(t("Sign in",27,true,Color.WHITE));box.addView(t("Use the Xtream credentials from your provider",12,false,Color.rgb(126,133,150)).apply{setPadding(0,dp(4),0,dp(8))});val es=e("Server URL",server,false);val eu=e("Username",user,false);val ep=e("Password",pass,true);box.addView(es);box.addView(eu);box.addView(ep);val status=t("",12,false,Color.LTGRAY);box.addView(status);val go=btn("CONTINUE",Color.WHITE,Color.BLACK);go.setOnClickListener{val s=es.text.toString().trim();val u=eu.text.toString().trim();val p=ep.text.toString();if(s.isBlank()||u.isBlank()||p.isBlank()){status.text="Complete all fields";return@setOnClickListener};go.isEnabled=false;status.text="Connecting…";io.execute{try{val j=IptvRepository(s,u,p).authenticate();if((j.optJSONObject("user_info")?.optInt("auth",0)?:0)!=1)error("Account not accepted");server=s.trimEnd('/');user=u;pass=p;prefs.edit().putString("server",server).putString("user",user).putString("pass",pass).apply();repo=IptvRepository(server,user,pass);runOnUiThread{home()}}catch(x:Exception){runOnUiThread{go.isEnabled=true;status.text="Connection failed • ${x.message}"}}}};box.addView(go,LinearLayout.LayoutParams(-1,dp(52)).apply{topMargin=dp(12)});root.addView(box,LinearLayout.LayoutParams(0,-1,.85f));setContentView(root)}

    private fun home(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(28),dp(16),dp(28),dp(16))};val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};top.addView(t("ADAM IPTV",20,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f));top.addView(nav("LIVE"){browser("live")});top.addView(nav("MOVIES"){browser("vod")});top.addView(nav("SERIES"){browser("series")});top.addView(nav("FAVORITES"){favorites()});top.addView(nav("⚙"){settings()});root.addView(top);val sc=ScrollView(this);val content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};content.addView(t("Your library",28,true,Color.WHITE).apply{setPadding(0,dp(24),0,dp(4))});content.addView(t("Browse your own channels and on-demand content",13,false,Color.rgb(115,122,138)).apply{setPadding(0,0,0,dp(16))});addShelf(content,"Live now","live");addShelf(content,"Movies","vod");addShelf(content,"Series","series");sc.addView(content);root.addView(sc,LinearLayout.LayoutParams(-1,0,1f));setContentView(root)}
    private fun addShelf(parent:LinearLayout,title:String,kind:String){val head=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};head.addView(t(title,19,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f));val more=t("VIEW ALL  ›",11,true,gold).apply{setPadding(dp(12),dp(8),dp(12),dp(8));setOnClickListener{browser(kind)}};head.addView(more);parent.addView(head);val rv=RecyclerView(this).apply{layoutManager=LinearLayoutManager(this@MainActivity,RecyclerView.HORIZONTAL,false);setPadding(0,dp(10),0,dp(18));clipToPadding=false};val ad=ContentAdapter(kind, mutableListOf(),{open(it)},{toggle(it)});rv.adapter=ad;parent.addView(rv,LinearLayout.LayoutParams(-1,if(kind=="live")dp(180) else dp(275)));io.execute{try{val data=repo!!.items(kind).take(14);runOnUiThread{ad.replace(data)}}catch(_:Exception){}}}

    private fun browser(kind:String){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(24),dp(14),dp(24),dp(16))};val bar=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val back=nav("‹ BACK"){home()};bar.addView(back);bar.addView(t(when(kind){"live"->"Live TV";"vod"->"Movies";else->"Series"},25,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f).apply{marginStart=dp(18)});val search=e("Search","",false);bar.addView(search,LinearLayout.LayoutParams(dp(280),dp(46)));root.addView(bar);val cats=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val catScroll=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;addView(cats)};root.addView(catScroll,LinearLayout.LayoutParams(-1,dp(58)).apply{topMargin=dp(12)});val rv=RecyclerView(this);rv.layoutManager=GridLayoutManager(this,if(kind=="live")4 else 5);root.addView(rv,LinearLayout.LayoutParams(-1,0,1f));setContentView(root);var all:List<IptvRepository.Item> = emptyList();var selected="all";val ad=ContentAdapter(kind,mutableListOf(),{open(it)},{toggle(it)});rv.adapter=ad;fun render(){ad.replace(all.filter{(selected=="all"||it.categoryId==selected)&&it.name.contains(search.text.toString(),true)})};search.addTextChangedListener(object:TextWatcher{override fun afterTextChanged(s:Editable?){render()};override fun beforeTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){}});io.execute{try{val c=repo!!.categories(kind);val items=repo!!.items(kind);runOnUiThread{all=items;c.forEach{x->val b=chip(x.name);b.setOnClickListener{selected=x.id;render()};cats.addView(b,LinearLayout.LayoutParams(-2,dp(40)).apply{marginEnd=dp(8)})};render()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,"Unable to load: ${x.message}",Toast.LENGTH_LONG).show()}}}}

    private fun open(i:IptvRepository.Item){if(i.kind=="series")episodes(i)else play(repo!!.streamUrl(i),i.name)}
    private fun episodes(s:IptvRepository.Item){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(26),dp(16),dp(26),dp(16))};val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};top.addView(nav("‹ SERIES"){browser("series")});top.addView(t(s.name,24,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f).apply{marginStart=dp(18)});root.addView(top);val rv=RecyclerView(this).apply{layoutManager=LinearLayoutManager(this@MainActivity)};root.addView(rv,LinearLayout.LayoutParams(-1,0,1f).apply{topMargin=dp(14)});setContentView(root);io.execute{try{val eps=repo!!.episodes(s.id);runOnUiThread{rv.adapter=EpisodeAdapter(eps){play(repo!!.episodeUrl(it),it.title)}}}catch(x:Exception){runOnUiThread{Toast.makeText(this,"Unable to load episodes",Toast.LENGTH_LONG).show()}}}}
    private fun favorites(){val raw=prefs.getStringSet("favorites",emptySet())?:emptySet();val items=raw.mapNotNull{try{val o=JSONObject(it);IptvRepository.Item(o.getString("id"),o.getString("name"),o.optString("icon"),o.optString("ext"),o.optString("cat"),o.getString("kind"))}catch(_:Exception){null}};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(dp(24),dp(14),dp(24),dp(16))};val top=LinearLayout(this);top.addView(nav("‹ HOME"){home()});top.addView(t("Favorites",25,true,Color.WHITE),LinearLayout.LayoutParams(0,-2,1f).apply{marginStart=dp(18)});root.addView(top);val rv=RecyclerView(this).apply{layoutManager=GridLayoutManager(this@MainActivity,5);adapter=ContentAdapter("vod",items.toMutableList(),{open(it)},{toggle(it)})};root.addView(rv,LinearLayout.LayoutParams(-1,0,1f).apply{topMargin=dp(14)});setContentView(root)}
    private fun settings(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setBackgroundColor(bg)};root.addView(t("Account",28,true,Color.WHITE));root.addView(t("$user\n$server\n\nVersion 1.2.0",14,false,Color.rgb(145,152,168)).apply{gravity=Gravity.CENTER;setPadding(0,dp(18),0,dp(22))});val back=btn("BACK",Color.WHITE,Color.BLACK);back.setOnClickListener{home()};root.addView(back,LinearLayout.LayoutParams(dp(240),dp(50)));val out=btn("REMOVE ACCOUNT",Color.rgb(103,36,47),Color.WHITE);out.setOnClickListener{prefs.edit().remove("server").remove("user").remove("pass").apply();server="";user="";pass="";repo=null;login()};root.addView(out,LinearLayout.LayoutParams(dp(240),dp(50)).apply{topMargin=dp(10)});setContentView(root)}
    private fun play(url:String,title:String){startActivity(Intent(this,PlayerActivity::class.java).putExtra("url",url).putExtra("title",title))}
    private fun toggle(i:IptvRepository.Item){val s=(prefs.getStringSet("favorites",emptySet())?:emptySet()).toMutableSet();val old=s.firstOrNull{try{val o=JSONObject(it);o.optString("id")==i.id&&o.optString("kind")==i.kind}catch(_:Exception){false}};if(old==null)s.add(JSONObject().put("id",i.id).put("name",i.name).put("icon",i.icon).put("ext",i.extension).put("cat",i.categoryId).put("kind",i.kind).toString())else s.remove(old);prefs.edit().putStringSet("favorites",s).apply();Toast.makeText(this,if(old==null)"Added to favorites" else "Removed from favorites",Toast.LENGTH_SHORT).show()}
    private fun nav(s:String,a:()->Unit)=TextView(this).apply{text=s;textSize=11f;setTextColor(Color.rgb(204,209,220));typeface=Typeface.DEFAULT_BOLD;gravity=Gravity.CENTER;setPadding(dp(14),dp(10),dp(14),dp(10));setOnClickListener{a()}}
    private fun chip(s:String)=TextView(this).apply{text=s;textSize=11f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD;gravity=Gravity.CENTER;background=round(soft,18);setPadding(dp(16),0,dp(16),0)}
    private fun t(s:String,z:Int,b:Boolean,c:Int)=TextView(this).apply{text=s;textSize=z.toFloat();setTextColor(c);if(b)typeface=Typeface.DEFAULT_BOLD}
    private fun e(h:String,v:String,secret:Boolean)=EditText(this).apply{hint=h;setHintTextColor(Color.rgb(95,102,119));setTextColor(Color.WHITE);setText(v);setSingleLine();textSize=14f;background=round(soft,12);setPadding(dp(15),0,dp(15),0);if(secret)inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD;layoutParams=LinearLayout.LayoutParams(-1,dp(50)).apply{topMargin=dp(9)}}
    private fun btn(s:String,bg:Int,fg:Int)=Button(this).apply{text=s;setTextColor(fg);textSize=12f;typeface=Typeface.DEFAULT_BOLD;isAllCaps=false;background=round(bg,12)}
    private fun round(c:Int,r:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat()};private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();override fun onDestroy(){super.onDestroy();io.shutdownNow()}
}
